[identity]
id = "dummy"
name = "Dummy Example Model"
description = "An example of the WPL Meteo Model class in action"
information_url = "https://bull.crap"
license_information = "Just do whatever"

[properties]
predictive_model = false
directly_accessible = true
storage_mode_to_use = "NO_STORAGE"
singular_datapoint = false

[geography]
time_range_start = "2022-01-01"
time_range_end = "2024-04-04"
area_bounding_box = [0.0, 0.0, 0.0, 0.0]
source_crs = "EPSG:4326"
