gitGraph
    commit id: "main version 1.2"
    branch release-v1.3
    checkout release-v1.3
    commit id: "initial release-v1.3"
    branch feature_a
    checkout feature_a
    commit id: "first commit"
    commit id: "second commit"
    checkout release-v1.3
    branch feature_b
    checkout feature_b
    commit id: "first commit"
    checkout release-v1.3
    merge feature_b id: "PR Feature B"
    merge feature_a id: "PR Feature A"
    checkout main
    merge release-v1.3 id: "Release of V1.3"